# Generated by Django 5.2.5 on 2025-09-26 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='modified_at')),
                ('active', models.BooleanField(db_column='cs_active', default=True)),
                ('title', models.CharField(db_column='tx_title', max_length=255)),
                ('date', models.DateField(db_column='dt_date')),
                ('author', models.ForeignKey(db_column='id_author', on_delete=django.db.models.deletion.PROTECT, to='core.author')),
            ],
            options={
                'verbose_name': 'Album',
                'verbose_name_plural': 'Albums',
                'db_table': 'album',
            },
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='modified_at')),
                ('active', models.BooleanField(db_column='cs_active', default=True)),
                ('title', models.CharField(db_column='tx_title', max_length=255)),
                ('duration', models.DurationField(db_column='tm_duration')),
                ('album', models.ForeignKey(db_column='id_album', on_delete=django.db.models.deletion.CASCADE, to='core.album')),
            ],
            options={
                'verbose_name': 'Music',
                'verbose_name_plural': 'Musics',
                'db_table': 'music',
            },
        ),
    ]
